using System.Collections.Generic;

namespace ClassicalCompendium
{
    public class PresetLists
    {
        public class Time
        {
            public static List<string> Months = new List<string>
            {
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December"
            };

            public static List<string> WeekDays = new List<string>
            {
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday"
            };

            public static List<string> Hours = new List<string>
            {
                "12 PM",
                "1 AM",
                "2 AM",
                "3 AM",
                "4 AM",
                "5 AM",
                "6 AM",
                "7 AM",
                "8 AM",
                "9 AM",
                "10 AM",
                "11 AM",
                "12 AM",
                "1 PM",
                "2 PM",
                "3 PM",
                "4 PM",
                "5 PM",
                "6 PM",
                "7 PM",
                "8 PM",
                "9 PM",
                "10 PM",
                "11 PM"
            };
        }

        public class Countries
        {
            public static List<(string, string, string, int)> CountryISO = new List<(string, string, string, int)>
            {
                ("Afghanistan", "AF", "AFG", 4),
                ("Åland Islands", "AX", "ALA", 248),
                ("Albania", "AL", "ALB", 8),
                ("Algeria", "DZ", "DZA", 12),
                ("American Samoa", "AS", "ASM", 16),
                ("Andorra", "AD", "AND", 20),
                ("Angola", "AO", "AGO", 24),
                ("Anguilla", "AI", "AIA", 660),
                ("Antarctica", "AQ", "ATA", 10),
                ("Antigua and Barbuda", "AG", "ATG", 28),
                ("Argentina", "AR", "ARG", 32),
                ("Armenia", "AM", "ARM", 51),
                ("Aruba", "AW", "ABW", 533),
                ("Australia", "AU", "AUS", 36),
                ("Austria", "AT", "AUT", 40),
                ("Azerbaijan", "AZ", "AZE", 31),
                ("Bahamas", "BS", "BHS", 44),
                ("Bahrain", "BH", "BHR", 48),
                ("Bangladesh", "BD", "BGD", 50),
                ("Barbados", "BB", "BRB", 52),
                ("Belarus", "BY", "BLR", 112),
                ("Belgium", "BE", "BEL", 56),
                ("Belize", "BZ", "BLZ", 84),
                ("Benin", "BJ", "BEN", 204),
                ("Bermuda", "BM", "BMU", 60),
                ("Bhutan", "BT", "BTN", 64),
                ("Bolivia (Plurinational State of)", "BO", "BOL", 68),
                ("Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535),
                ("Bosnia and Herzegovina", "BA", "BIH", 70),
                ("Botswana", "BW", "BWA", 72),
                ("Bouvet Island", "BV", "BVT", 74),
                ("Brazil", "BR", "BRA", 76),
                ("British Indian Ocean Territory", "IO", "IOT", 86),
                ("Brunei Darussalam", "BN", "BRN", 96),
                ("Bulgaria", "BG", "BGR", 100),
                ("Burkina Faso", "BF", "BFA", 854),
                ("Burundi", "BI", "BDI", 108),
                ("Cabo Verde", "CV", "CPV", 132),
                ("Cambodia", "KH", "KHM", 116),
                ("Cameroon", "CM", "CMR", 120),
                ("Canada", "CA", "CAN", 124),
                ("Cayman Islands", "KY", "CYM", 136),
                ("Central African Republic", "CF", "CAF", 140),
                ("Chad", "TD", "TCD", 148),
                ("Chile", "CL", "CHL", 152),
                ("China", "CN", "CHN", 156),
                ("Christmas Island", "CX", "CXR", 162),
                ("Cocos (Keeling) Islands", "CC", "CCK", 166),
                ("Colombia", "CO", "COL", 170),
                ("Comoros", "KM", "COM", 174),
                ("Congo", "CG", "COG", 178),
                ("Congo, Democratic Republic of the", "CD", "COD", 180),
                ("Cook Islands", "CK", "COK", 184),
                ("Costa Rica", "CR", "CRI", 188),
                ("Côte d'Ivoire", "CI", "CIV", 384),
                ("Croatia", "HR", "HRV", 191),
                ("Cuba", "CU", "CUB", 192),
                ("Curaçao", "CW", "CUW", 531),
                ("Cyprus", "CY", "CYP", 196),
                ("Czechia", "CZ", "CZE", 203),
                ("Denmark", "DK", "DNK", 208),
                ("Djibouti", "DJ", "DJI", 262),
                ("Dominica", "DM", "DMA", 212),
                ("Dominican Republic", "DO", "DOM", 214),
                ("Ecuador", "EC", "ECU", 218),
                ("Egypt", "EG", "EGY", 818),
                ("El Salvador", "SV", "SLV", 222),
                ("Equatorial Guinea", "GQ", "GNQ", 226),
                ("Eritrea", "ER", "ERI", 232),
                ("Estonia", "EE", "EST", 233),
                ("Eswatini", "SZ", "SWZ", 748),
                ("Ethiopia", "ET", "ETH", 231),
                ("Falkland Islands (Malvinas)", "FK", "FLK", 238),
                ("Faroe Islands", "FO", "FRO", 234),
                ("Fiji", "FJ", "FJI", 242),
                ("Finland", "FI", "FIN", 246),
                ("France", "FR", "FRA", 250),
                ("French Guiana", "GF", "GUF", 254),
                ("French Polynesia", "PF", "PYF", 258),
                ("French Southern Territories", "TF", "ATF", 260),
                ("Gabon", "GA", "GAB", 266),
                ("Gambia", "GM", "GMB", 270),
                ("Georgia", "GE", "GEO", 268),
                ("Germany", "DE", "DEU", 276),
                ("Ghana", "GH", "GHA", 288),
                ("Gibraltar", "GI", "GIB", 292),
                ("Greece", "GR", "GRC", 300),
                ("Greenland", "GL", "GRL", 304),
                ("Grenada", "GD", "GRD", 308),
                ("Guadeloupe", "GP", "GLP", 312),
                ("Guam", "GU", "GUM", 316),
                ("Guatemala", "GT", "GTM", 320),
                ("Guernsey", "GG", "GGY", 831),
                ("Guinea", "GN", "GIN", 324),
                ("Guinea-Bissau", "GW", "GNB", 624),
                ("Guyana", "GY", "GUY", 328),
                ("Haiti", "HT", "HTI", 332),
                ("Heard Island and McDonald Islands", "HM", "HMD", 334),
                ("Holy See", "VA", "VAT", 336),
                ("Honduras", "HN", "HND", 340),
                ("Hong Kong", "HK", "HKG", 344),
                ("Hungary", "HU", "HUN", 348),
                ("Iceland", "IS", "ISL", 352),
                ("India", "IN", "IND", 356),
                ("Indonesia", "ID", "IDN", 360),
                ("Iran (Islamic Republic of)", "IR", "IRN", 364),
                ("Iraq", "IQ", "IRQ", 368),
                ("Ireland", "IE", "IRL", 372),
                ("Isle of Man", "IM", "IMN", 833),
                ("Israel", "IL", "ISR", 376),
                ("Italy", "IT", "ITA", 380),
                ("Jamaica", "JM", "JAM", 388),
                ("Japan", "JP", "JPN", 392),
                ("Jersey", "JE", "JEY", 832),
                ("Jordan", "JO", "JOR", 400),
                ("Kazakhstan", "KZ", "KAZ", 398),
                ("Kenya", "KE", "KEN", 404),
                ("Kiribati", "KI", "KIR", 296),
                ("Korea (Democratic People's Republic of)", "KP", "PRK", 408),
                ("Korea, Republic of", "KR", "KOR", 410),
                ("Kuwait", "KW", "KWT", 414),
                ("Kyrgyzstan", "KG", "KGZ", 417),
                ("Lao People's Democratic Republic", "LA", "LAO", 418),
                ("Latvia", "LV", "LVA", 428),
                ("Lebanon", "LB", "LBN", 422),
                ("Lesotho", "LS", "LSO", 426),
                ("Liberia", "LR", "LBR", 430),
                ("Libya", "LY", "LBY", 434),
                ("Liechtenstein", "LI", "LIE", 438),
                ("Lithuania", "LT", "LTU", 440),
                ("Luxembourg", "LU", "LUX", 442),
                ("Macao", "MO", "MAC", 446),
                ("Madagascar", "MG", "MDG", 450),
                ("Malawi", "MW", "MWI", 454),
                ("Malaysia", "MY", "MYS", 458),
                ("Maldives", "MV", "MDV", 462),
                ("Mali", "ML", "MLI", 466),
                ("Malta", "MT", "MLT", 470),
                ("Marshall Islands", "MH", "MHL", 584),
                ("Martinique", "MQ", "MTQ", 474),
                ("Mauritania", "MR", "MRT", 478),
                ("Mauritius", "MU", "MUS", 480),
                ("Mayotte", "YT", "MYT", 175),
                ("Mexico", "MX", "MEX", 484),
                ("Micronesia (Federated States of)", "FM", "FSM", 583),
                ("Moldova, Republic of", "MD", "MDA", 498),
                ("Monaco", "MC", "MCO", 492),
                ("Mongolia", "MN", "MNG", 496),
                ("Montenegro", "ME", "MNE", 499),
                ("Montserrat", "MS", "MSR", 500),
                ("Morocco", "MA", "MAR", 504),
                ("Mozambique", "MZ", "MOZ", 508),
                ("Myanmar", "MM", "MMR", 104),
                ("Namibia", "NA", "NAM", 516),
                ("Nauru", "NR", "NRU", 520),
                ("Nepal", "NP", "NPL", 524),
                ("Netherlands", "NL", "NLD", 528),
                ("New Caledonia", "NC", "NCL", 540),
                ("New Zealand", "NZ", "NZL", 554),
                ("Nicaragua", "NI", "NIC", 558),
                ("Niger", "NE", "NER", 562),
                ("Nigeria", "NG", "NGA", 566),
                ("Niue", "NU", "NIU", 570),
                ("Norfolk Island", "NF", "NFK", 574),
                ("North Macedonia", "MK", "MKD", 807),
                ("Northern Mariana Islands", "MP", "MNP", 580),
                ("Norway", "NO", "NOR", 578),
                ("Oman", "OM", "OMN", 512),
                ("Pakistan", "PK", "PAK", 586),
                ("Palau", "PW", "PLW", 585),
                ("Palestine", "PS", "PSE", 275),
                ("Panama", "PA", "PAN", 591),
                ("Papua New Guinea", "PG", "PNG", 598),
                ("Paraguay", "PY", "PRY", 600),
                ("Peru", "PE", "PER", 604),
                ("Philippines", "PH", "PHL", 608),
                ("Pitcairn", "PN", "PCN", 612),
                ("Poland", "PL", "POL", 616),
                ("Portugal", "PT", "PRT", 620),
                ("Puerto Rico", "PR", "PRI", 630),
                ("Qatar", "QA", "QAT", 634),
                ("Réunion", "RE", "REU", 638),
                ("Romania", "RO", "ROU", 642),
                ("Russian Federation", "RU", "RUS", 643),
                ("Rwanda", "RW", "RWA", 646),
                ("Saint Barthelemy", "BL", "BLM", 652),
                ("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654),
                ("Saint Kitts and Nevis", "KN", "KNA", 659),
                ("Saint Lucia", "LC", "LCA", 662),
                ("Saint Martin (French part)", "MF", "MAF", 663),
                ("Saint Pierre and Miquelon", "PM", "SPM", 666),
                ("Saint Vincent and the Grenadines", "VC", "VCT", 670),
                ("Samoa", "WS", "WSM", 882),
                ("San Marino", "SM", "SMR", 674),
                ("Sao Tome and Principe", "ST", "STP", 678),
                ("Saudi Arabia", "SA", "SAU", 682),
                ("Senegal", "SN", "SEN", 686),
                ("Serbia", "RS", "SRB", 688),
                ("Seychelles", "SC", "SYC", 690),
                ("Sierra Leone", "SL", "SLE", 694),
                ("Singapore", "SG", "SGP", 702),
                ("Sint Maarten (Dutch part)", "SX", "SXM", 534),
                ("Slovakia", "SK", "SVK", 703),
                ("Slovenia", "SI", "SVN", 705),
                ("Solomon Islands", "SB", "SLB", 90),
                ("Somalia", "SO", "SOM", 706),
                ("South Africa", "ZA", "ZAF", 710),
                ("South Georgia and the South Sandwich Islands", "GS", "SGS", 239),
                ("South Sudan", "SS", "SSD", 728),
                ("Spain", "ES", "ESP", 724),
                ("Sri Lanka", "LK", "LKA", 144),
                ("Sudan", "SD", "SDN", 729),
                ("Suriname", "SR", "SUR", 740),
                ("Svalbard and Jan Mayen", "SJ", "SJM", 744),
                ("Sweden", "SE", "SWE", 752),
                ("Switzerland", "CH", "CHE", 756),
                ("Syrian Arab Republic", "SY", "SYR", 760),
                ("Taiwan", "TW", "TWN", 158),
                ("Tajikistan", "TJ", "TJK", 762),
                ("Tanzania, United Republic of", "TZ", "TZA", 834),
                ("Thailand", "TH", "THA", 764),
                ("Timor-Leste", "TL", "TLS", 626),
                ("Togo", "TG", "TGO", 768),
                ("Tokelau", "TK", "TKL", 772),
                ("Tonga", "TO", "TON", 776),
                ("Trinidad and Tobago", "TT", "TTO", 780),
                ("Tunisia", "TN", "TUN", 788),
                ("Turkey", "TR", "TUR", 792),
                ("Turkmenistan", "TM", "TKM", 795),
                ("Turks and Caicos Islands", "TC", "TCA", 796),
                ("Tuvalu", "TV", "TUV", 798),
                ("Uganda", "UG", "UGA", 800),
                ("Ukraine", "UA", "UKR", 804),
                ("United Arab Emirates", "AE", "ARE", 784),
                ("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", 826),
                ("United States of America", "US", "USA", 840),
                ("Uruguay", "UY", "URY", 858),
                ("Uzbekistan", "UZ", "UZB", 860),
                ("Vanuatu", "VU", "VUT", 548),
                ("Venezuela (Bolivarian Republic of)", "VE", "VEN", 862),
                ("Viet Nam", "VN", "VNM", 704),
                ("Virgin Islands (British)", "VG", "VGB", 92),
                ("Virgin Islands (U.S.)", "VI", "VIR", 850),
                ("Wallis and Futuna", "WF", "WLF", 876),
                ("Western Sahara", "EH", "ESH", 732),
                ("Yemen", "YE", "YEM", 887),
                ("Zambia", "ZM", "ZMB", 894),
                ("Zimbabwe", "ZW", "ZWE", 716)
            };

            public static List<string> MostUsedLangages = new List<string>
            {
                "English",
                "French",
                "Arabic",
                "Standard Chinese",
                "Spanish",
                "Persian",
                "German",
                "Russian",
                "Malay",
                "Portuguese"
            };

            public static List<string> OfficialLanguages = new List<string>
            {
                "Abkhaz",
                "Afar",
                "Afrikaans",
                "Aja-Gbe",
                "Akan",
                "Albanian",
                "Amharic",
                "Anii",
                "Arabic",
                "Armenian",
                "Assamese",
                "Aymara",
                "Azerbaijani",
                "Balanta",
                "Bambara",
                "Bariba",
                "Basque",
                "Bassari",
                "Bedik",
                "Belarusian",
                "Bengali",
                "Berber",
                "Biali",
                "Bislama",
                "Boko",
                "Bomu",
                "Bosnian",
                "Bozo",
                "Buduma",
                "Bulgarian",
                "Burmese",
                "Cantonese",
                "Catalan",
                "Chinese (Mandarin)",
                "Chichewa",
                "Chirbawe",
                "Comorian",
                "Corsican",
                "Croatian",
                "Czech",
                "Dagaare",
                "Dagbani",
                "Dangme",
                "Danish",
                "Dari",
                "Dendi",
                "Dhivehi",
                "Dioula",
                "Dogon",
                "Dutch",
                "Dzongkha",
                "English",
                "Estonian",
                "Ewe-Gbe",
                "Faroese",
                "Fijian",
                "Filipino",
                "Finnish",
                "Fon-Gbe",
                "Foodo",
                "Formosan",
                "French",
                "Fula",
                "Ga",
                "Gàidhlig",
                "Gbe",
                "Gen-Gbe",
                "Georgian",
                "German",
                "Gonja",
                "Gourmanché",
                "Greek",
                "Guarani",
                "Gujarati",
                "Haitian Creole",
                "Hakka",
                "Hassaniya",
                "Hausa",
                "Hebrew",
                "Hindi",
                "Hiri Motu",
                "Hungarian",
                "Igbo",
                "Icelandic",
                "Indonesian",
                "Irish",
                "Italian",
                "Japanese",
                "Javanese",
                "Jola",
                "Kabye",
                "Kalanga",
                "Kannada",
                "Kanuri",
                "Kasem",
                "Kazakh",
                "Khmer",
                "Kinyarwanda",
                "Kirundi",
                "Kissi",
                "Koisan",
                "Korean",
                "Kpelle",
                "Kurdish",
                "Kyrgyz",
                "Lao",
                "Latin",
                "Latvian",
                "Lituanian",
                "Lukpa",
                "Luxembourgish",
                "Macedonian",
                "Malagasy",
                "Malay",
                "Malinke",
                "Maltese",
                "Mamara",
                "Manding",
                "Mandinka",
                "Mandjak",
                "Mankanya",
                "Manx Gaelic",
                "Maori",
                "Marshallese",
                "Mauritian Creole",
                "Mbelime",
                "Meitei",
                "Mongolian",
                "Montenegrin",
                "Mossi",
                "Nambya",
                "Nateni",
                "Nauruan",
                "Ndau",
                "Ndebele",
                "Nepali",
                "Noon",
                "Northern Sotho",
                "Norwegian",
                "Nzema",
                "Oniyan",
                "Oriya",
                "Oromo",
                "Ossetian",
                "Palauan",
                "Papiamento",
                "Pashto",
                "Persian",
                "Polish",
                "Portuguese",
                "Punjabi",
                "Quechua",
                "Romanian",
                "Romansch",
                "Russian",
                "Safen",
                "Samoa",
                "Sango",
                "Sena",
                "Scots",
                "Serbian",
                "Serer",
                "Seychellois Creole",
                "Shona",
                "Sinhala",
                "Slovak",
                "Slovene",
                "Somali",
                "Songhay-Zarma",
                "Soninke",
                "Sotho",
                "Spanish",
                "Susu",
                "Swahili",
                "Swati",
                "Swedish",
                "Syenara",
                "Taiwanese Hokkien",
                "Tajik",
                "Tagalog",
                "Tamasheq",
                "Tamil",
                "Tammari",
                "Tasawaq",
                "Tebu",
                "Telugu",
                "Tetum",
                "Thai",
                "Tigrinya",
                "Tok Pisin",
                "Toma",
                "Tonga",
                "Tongan",
                "Tsonga",
                "Tswana",
                "Turkish",
                "Turkmen",
                "Tuvaluan",
                "Ukrainian",
                "Urdu",
                "Uzbek",
                "Venda",
                "Vietnamese",
                "Waama",
                "Waci-Gbe",
                "Wamey",
                "Welsh",
                "Wolof",
                "Xhosa",
                "Xwela-Gbe",
                "Yobe",
                "Yom",
                "Yoruba",
                "Zulu"
            };
        }

        public class Chars
        {
            public static Dictionary<char, string> ReverseAlphabet = new Dictionary<char, string>{
              { 'A', "Z" }, { 'B', "Y" }, { 'C', "X" },
              { 'D', "W" }, { 'E', "V "}, { 'F', "U" },
              { 'G', "T" }, { 'H', "S" }, { 'I', "R" },
              { 'J', "Q" }, { 'K', "P" }, { 'L', "O" },
              { 'M', "N" }, { 'N', "M" }, { 'O', "L" },
              { 'P', "K" }, { 'Q', "J" }, { 'R', "I" },
              { 'S', "H" }, { 'T', "G" }, { 'U', "F" },
              { 'V', "E" }, { 'W', "D" }, { 'X', "C" },
              { 'Y', "B" }, { 'Z', "A" }
            };

            public static List<(string, int)> OrderOfMagnitude = new List<(string, int)>
            {
                ("quecto", -30),
                ("ronto", -27),
                ("yocto", -24),
                ("zepto", -21),
                ("atto", -18),
                ("femto", -15),
                ("pico", -12),
                ("nano", -9),
                ("micro", -6),
                ("milli", -3),
                ("centi", -2),
                ("deci", -1),
                ("deca", 1),
                ("hecto", 2),
                ("kilo", 3),
                ("mega", 6),
                ("giga", 9),
                ("tera", 12),
                ("peta", 15),
                ("exa", 18),
                ("zetta", 21),
                ("yotta", 24),
                ("ronna", 27),
                ("quetta", 30)
            };
        }

        public class Numbers
        {
            public List<(string, string)> HexadecimalNumbers = new List<(string, string)>
            {
                ("0", "0"), ("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"),
                ("6", "6"), ("7", "7"), ("8", "8"), ("9", "9"), ("10", "A"),("11", "B"),
                ("12", "C"), ("13", "D"), ("14", "E"), ("15", "F"),
                ("16", "10"), ("17", "11"), ("18", "12"), ("19", "13"), ("20", "14"),
                ("21", "15"), ("22", "16"), ("23", "17"), ("24", "18"), ("25", "19"),
                ("26", "1A"), ("27", "1B"), ("28", "1C"), ("29", "1D"), ("30", "1E"),
                ("31", "1F"), ("32", "20"), ("33", "21"), ("34", "22"), ("35", "23"),
                ("36", "24"), ("37", "25"), ("38", "26"), ("39", "27"), ("40", "28"),
                ("41", "29"), ("42", "2A"), ("43", "2B"), ("44", "2C"), ("45", "2D"),
                ("46", "2E"), ("47", "2F"), ("48", "30"), ("49", "31"), ("50", "32"),
                ("51", "33"), ("52", "34"), ("53", "35"), ("54", "36"), ("55", "37"),
                ("56", "38"), ("57", "39"), ("58", "3A"), ("59", "3B"), ("60", "3C"),
                ("61", "3D"), ("62", "3E"), ("63", "3F"), ("64", "40"), ("65", "41"),
                ("66", "42"), ("67", "43"), ("68", "44"), ("69", "45"), ("70", "46"),
                ("71", "47"), ("72", "48"), ("73", "49"), ("74", "4A"), ("75", "4B"),
                ("76", "4C"), ("77", "4D"), ("78", "4E"), ("79", "4F"), ("80", "50"),
                ("81", "51"), ("82", "52"), ("83", "53"), ("84", "54"), ("85", "55"),
                ("86", "56"), ("87", "57"), ("88", "58"), ("89", "59"), ("90", "5A"),
                ("91", "5B"), ("92", "5C"), ("93", "5D"), ("94", "5E"), ("95", "5F"),
                ("96", "60"), ("97", "61"), ("98", "62"), ("99", "63"), ("100", "64"),
                ("101", "65"), ("102", "66"), ("103", "67"), ("104", "68"), ("105", "69"),
                ("106", "6A"), ("107", "6B"), ("108", "6C"), ("109", "6D"), ("110", "6E"),
                ("111", "6F"), ("112", "70"), ("113", "71"), ("114", "72"), ("115", "73"),
                ("116", "74"), ("117", "75"), ("118", "76"), ("119", "77"), ("120", "78"),
                ("121", "79"), ("122", "7A"), ("123", "7B"), ("124", "7C"), ("125", "7D"),
                ("126", "7E"), ("127", "7F"), ("128", "80"), ("129", "81"), ("130", "82"),
                ("131", "83"), ("132", "84"), ("133", "85"), ("134", "86"), ("135", "87"),
                ("136", "88"), ("137", "89"), ("138", "8A"), ("139", "8B"), ("140", "8C"),
                ("141", "8D"), ("142", "8E"), ("143", "8F"), ("144", "90"), ("145", "91"),
                ("146", "92"), ("147", "93"), ("148", "94"), ("149", "95"), ("150", "96"),
                ("151", "97"), ("152", "98"), ("153", "99"), ("154", "9A"), ("155", "9B"),
                ("156", "9C"), ("157", "9D"), ("158", "9E"), ("159", "9F"), ("160", "A0"),
                ("161", "A1"), ("162", "A2"), ("163", "A3"), ("164", "A4"), ("165", "A5"),
                ("166", "A6"), ("167", "A7"), ("168", "A8"), ("169", "A9"), ("170", "AA"),
                ("171", "AB"), ("172", "AC"), ("173", "AD"), ("174", "AE"), ("175", "AF"),
                ("176", "B0"), ("177", "B1"), ("178", "B2"), ("179", "B3"), ("180", "B4"),
                ("181", "B5"), ("182", "B6"), ("183", "B7"), ("184", "B8"), ("185", "B9"),
                ("186", "BA"), ("187", "BB"), ("188", "BC"), ("189", "BD"), ("190", "BE"),
                ("191", "BF"), ("192", "C0"), ("193", "C1"), ("194", "C2"), ("195", "C3"),
                ("196", "C4"), ("197", "C5"), ("198", "C6"), ("199", "C7"), ("200", "C8"),
                ("201", "C9"), ("202", "CA"), ("203", "CB"), ("204", "CC"), ("205", "CD"),
                ("206", "CE"), ("207", "CF"), ("208", "D0"), ("209", "D1"), ("210", "D2"),
                ("211", "D3"), ("212", "D4"), ("213", "D5"), ("214", "D6"), ("215", "D7"),
                ("216", "D8"), ("217", "D9"), ("218", "DA"), ("219", "DB"), ("220", "DC"),
                ("221", "DD"), ("222", "DE"), ("223", "DF"), ("224", "E0"), ("225", "E1"),
                ("226", "E2"), ("227", "E3"), ("228", "E4"), ("229", "E5"), ("230", "E6"),
                ("231", "E7"), ("232", "E8"), ("233", "E9"), ("234", "EA"), ("235", "EB"),
                ("236", "EC"), ("237", "ED"), ("238", "EE"), ("239", "EF"), ("240", "F0"),
                ("241", "F1"), ("242", "F2"), ("243", "F3"), ("244", "F4"), ("245", "F5"),
                ("246", "F6"), ("247", "F7"), ("248", "F8"), ("249", "F9"), ("250", "FA"),
                ("251", "FB"), ("252", "FC"), ("253", "FD"), ("254", "FE"), ("255", "FF"),
            };
        }
    }
}
